INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES
('advancedlockpick', 'Advanced Lockpick', 1, 0, 1, 750),
('advancedrifle', 'Assault Rifle', 1, 0, 1, 0),
('autoshotgun', 'Auto Shotgun', 1, 0, 1, 0),
('appistol', 'AP Pistol', 1, 0, 1, 10),
('assaultrifle', 'Assault Rifle', 1, 0, 1, 0),
('assaultrifle_mk2', 'Assault Rifle II', 1, 0, 1, 0),
('assaultshotgun', 'Assault Shotgun', 1, 0, 1, 0),
('assaultsmg', 'Assault SMG', 1, 0, 1, 0),
('ball', 'Ball', 1, 0, 1, 0),
('bat', 'Baseball Bat', 1, 0, 1, 350),
('battleaxe', 'Battle Axe', 1, 0, 1, 0),
('bullpuprifle', 'Bullpup Rifle', 1, 0, 1, 0),
('bullpuprifle_mk2', 'Famas', 1, 0, 1, 0),
('bullpupshotgun', 'Bullpup Shotgun', 1, 0, 1, 0),
('bzgas', 'Bz Gas', 1, 0, 1, 0),
('carbinerifle', 'Carbine Rifle', 1, 0, 1, 0),
('carbinerifle_mk2', 'Carbine Rifle II', 1, 0, 1, 0),
('combatmg', 'Combat MG', 1, 0, 1, 0),
('combatmg_mk2', 'Combat MG Mk II', 1, 0, 1, 0),
('combatpdw', 'Combat PDW', 1, 0, 1, 0),
('combatpistol', 'Combat Pistol', 1, 0, 1, 0),
('compactlauncher', 'Compact Launcher', 1, 0, 1, 0),
('compactrifle', 'Compact Rifle', 1, 0, 1, 0),
('crowbar', 'Crow Bar', 1, 0, 1, 0),
('dagger', 'Dagger', 1, 0, 1, 0),
('dbshotgun', 'Double Barrel', 1, 0, 1, 0),
('digiscanner', 'Digital Scanner', 1, 0, 1, 0),
('doubleaction', 'Double Action Revolver', 1, 0, 1, 0),
('fireextinguisher', 'Fire Extinguisher', 1, 0, 1, 0),
('firework', 'Firework', 1, 0, 1, 0),
('flare', 'Flare', 1, 0, 1, 0),
('flaregun', 'Flare Gun', 1, 0, 1, 0),
('flashlight', 'Flashlight', 1, 0, 1, 5),
('golfclub', 'Golf Club', 1, 0, 1, 45),
('grenade', 'Grenade', 1, 0, 1, 5),
('grenadelauncher', 'Grenade Launcher', 1, 0, 1, 5),
('gusenberg', 'Gusenberg', 1, 0, 1, 0),
('hammer', 'Hammer', 1, 0, 1, 150),
('hatchet', 'Hatchet', 1, 0, 1, 0),
('heavypistol', 'Heavy Pistol', 1, 0, 1, 0),
('heavyshotgun', 'Heavy Shotgun', 1, 0, 1, 0),
('heavysniper', 'Heavy Sniper', 1, 0, 1, 0),
('heavysniper_mk2', 'Heavy Sniper II', 1, 0, 1, 0),
('hominglauncher', 'Homing Launcher', 1, 0, 1, 0),
('knife', 'Knife', 1, 0, 1, 35),
('knuckle', 'Knuckledusters', 1, 0, 1, 0),
('machete', 'Machete', 1, 0, 1, 0),
('machinepistol', 'Machine Pistol', 1, 0, 1, 0),
('marksmanpistol', 'Marksman Pistol', 1, 0, 1, 0),
('marksmanrifle', 'Marksman Rifle', 1, 0, 1, 0),
('marksmanrifle_mk2', 'Marksman Rifle II', 1, 0, 1, 0),
('mg', 'MG', 1, 0, 1, 0),
('musket', 'Musket', 1, 0, 1, 0),
('microsmg', 'Micro SMG', 1, 0, 1, 0),
('minigun', 'MiniGun', 1, 0, 1, 0),
('minismg', 'Mini SMG', 1, 0, 1, 0),
('molotov', 'Molotov', 1, 0, 1, 0),
('nightstick', 'Nightstick', 1, 0, 1, 0),
('parachute', 'Parachute', 1, 0, 1, 0),
('petrolcan', 'Petrol Can', 1, 0, 1, 150),
('pipebomb', 'Pipe Bomb', 1, 0, 1, 0),
('pistol', 'Pistol', 1, 0, 1, 0),
('pistol50', 'Pistol 50', 1, 0, 1, 0),
('pistol_mk2', 'Pistol II', 1, 0, 1, 0),
('poolcue', 'Pool Cue', 1, 0, 1, 45),
('proxmine', 'Proximity Mine', 1, 0, 1, 0),
('pumpshotgun', 'Pump Shotgun', 1, 0, 1, 0),
('pumpshotgun_mk2', 'Pump Shotgun II', 1, 0, 1, 0),
('railgun', 'Railgun', 1, 0, 1, 0),
('revolver', 'Revolver', 1, 0, 1, 0),
('revolver_mk2', 'Revolver II', 1, 0, 1, 0),
('rpg', 'RPG', 1, 0, 1, 0),
('sawnoffshotgun', 'Sawn Off Shotgun', 1, 0, 1, 0),
('smg', 'SMG', 1, 0, 1, 0),
('smg_mk2', 'SMG II', 1, 0, 1, 0),
('sniperrifle', 'Sniper Rifle', 1, 0, 1, 0),
('snowball', 'Snow Ball', 1, 0, 1, 0),
('smokegrenade', 'Smoke Grenade', 1, 0, 1, 0),
('snspistol', 'SNS Pistol', 1, 0, 1, 0),
('snspistol_mk2', 'SNS Pistol II', 1, 0, 1, 0),
('specialcarbine', 'Special Carbine', 1, 0, 1, 0),
('specialcarbine_mk2', 'Special Carbine II', 1, 0, 1, 0),
('stungun', 'Stungun', 1, 0, 1, 0),
('stickybomb', 'Sticky Bomb', 1, 0, 1, 0),
('switchblade', 'Switchblade', 1, 0, 1, 0),
('vintagepistol', 'Vintage Pistol', 1, 0, 1, 0),
('wrench', 'Wrench', 1, 0, 1, 150);